apiVersion: v1
kind: Pod
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    tier: frontend
  annotations:
    description: "Pod with sidecar, ambassador, resource configs, env vars"
spec:
  containers:
  # Main container: NGINX
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: ENV
      value: "production"
    volumeMounts:
    - name: shared-logs
      mountPath: /usr/share/nginx/html

  # Sidecar container: Log simulator
  - name: log-sidecar
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - >
      while true; do
        echo "$(date) Access log line" >> /adapter/access.log;
        sleep 5;
      done
    volumeMounts:
    - name: shared-logs
      mountPath: /adapter

  # Ambassador container: Health checker
  - name: ambassador
    image: curlimages/curl
    command: ["/bin/sh", "-c"]
    args:
    - >
      while true; do
        echo "Ambassador: Checking NGINX...";
        curl -s http://localhost;
        sleep 10;
      done

  # Shared volume between containers
  volumes:
  - name: shared-logs
    emptyDir: {}
